### PR TITLE
Some timer fixes

### LINKED ISSUE #50: Incomplete session lifetime management (key rotation)
WireGuard protocol requirements for per-peer session lifetime based on the whitepaper:

 1. Sessions must no longer be used REJECT-AFTER-TIME (180 seconds). Data must not be sent when a session is expired and received data must be ignored.
 2. If an *initiator* sends data and session age >= REKEY-AFTER-TIME (120 seconds), it should attempt to start a new handshake.
 3. If a *responder* receives data and the session age is >= REJECT-AFTER-TIME - KEEPALIVE-TIMEOUT - REKEY-TIMEOUT (180 - 10 - 5 seconds), it should try to initiate a new handshake once for this event.
 4. After `REJECT-AFTER-TIME * 3`, all existing sessions must be destroyed.
 5. During key rotation, one must be able to decrypt data using the current and previous session (subject to the above REJECT-AFTER-TIME requirement), but previous sessions must be destroyed.

boringtun implements session retrieval and management in src/noise/timers.rs and src/noise/mod.rs.

Sessions are cleared only when:

 * `Tunn::set_static_private`: called when a new private key is set.
 * `Tunn::clear_all`: called when either:
    * The most recent established session is older than `REJECT-AFTER-TIME * 3` (established defined as receipt of an initiator/response message, not the 1.5-RTT data message for the responder!)
    * A new handshake was started by this device more than REKEY-ATTEMPT-TIME ago, but was not answered (handshake timeout).

Sessions are created on receipt of handshake messages in `network_to_tunnel`:
 * On receipt of a valid initiation message. Note that this session cannot be used yet since the `current` index has not yet been updated.
 * On receipt of a valid response handshake message that matches an existing in-progress handshake. Note that this session cannot be used yet since the `current` index has not yet been updated.

Sessions are used in:
 * `time_since_last_handshake` - uses the current session.
 * `tunnel_to_network` - uses the current session. Called when a locally-originated data packet is about to be sent.
 * `receive_data_packet` - uses the session based on the receiver index which is *chosen by the remote peer*.

The "current" session is updated in:
 * `network_to_tunnel` - when an initiator receives a handshake response.
 * `receive_data_packet` - when a data packet for an existing session is received and is successfully decrypted with a valid counter that is not reused.

Problems:
 1. The "current session" can be changed by the remote peer (or attacker) who sends a valid data packet. The "current session" should only be replaced when the a session is newer. Otherwise, consider this attack against the boringtun as initiator (a similar issue applies in the responder role):
    1. A honest boringtun initiator establishes a session with a responder and sends data. An attacker intercepts and withholds some data packets from the responder.
    2. The initiator (or responder) starts a new session due to key rotation and switches over to the new session.
    3. The attacker sends one of the data packets to the initiator, possibly **after REJECT-AFTER-TIME** has passed for the first session.
    4. The initiator switches the session secrets back to the old session, data sent by the initiator will not be protected with newer session secrets.
    5. This basically defeats key rotation and violates Requirement 1.
 2. Requirement 2 seems not fully implemented. If an initiator has sent data at some point, and after REKEY_AFTER_TIME, it should not automatically send an initiation message. Instead it should only trigger a new handshake right after sending a data message (including Keep-Alive). Right now it unconditionally sends an initiation message after REKEY-AFTER-TIME while it should have remained silent.
 3. Requirement 3 seems not fully implemented. `REJECT_AFTER_TIME - KEEPALIVE_TIMEOUT - REKEY_TIMEOUT` must be checked by the responder, but boringtun *only* checks it for the initiator.
 4. Requirement 4 seems satisfied but with one potential issue. As sessions are considered "established" right after receiving the Initiation message, the following attack is possible against a boringtun responder:
    1. Initiator starts handshake by sending an Initiation message. An attacker prevents these messages from arriving, so the initiator repeatedly sends new initiation messages.
    2. The attacker forwards the very *first* initiation message and thus establishes a session.
    3. Assume that the initiator no longer has data to send, so after `REJECT-AFTER-TIME * 3`, all sessions must be cleared.
    4. Just before it expires though, the attacker forwards the second initiation message. As this is not a replay, the boringtun responder assumes that a new session is established.
    5. This process can be repeated by an attacker using the remaining initiation messages.
    6. The result is that the session lifetimes can be prolonged.
5. Requirement 5 is not satisfied because previous sessions are not cleared.
6. (minor observation) `Tunn:tick_handshake_started` appears to be dead code, `Tunn::format_handshake_initiation` calls `self.timer_tick(TimerName::TimeLastHandshakeStarted)` directly.

Summary: Key rotation is not properly implemented, keys should have been cleared but are actual maintained for potentially a very long time. This might defeat forward secrecy when the boringtun client/server is raided since all keys are still in memory.

Note: this is based on a manual code review, I did not actually try to test the actual implementation.

Analysis applies to current master (commit e765e12613e8eb33e39e7fb0676ad5797c02c5f6).

### PR DESCRIPTION
**Pull request by vkrasnov**
* Add timers to clear each session after REJECT-AFTER-TIME seconds
* Correctly check for timer expiration after send and receive
* Increase number of sessions in the ring: in rare situations where both sides want to send a cookie we can get into a situation where no valid session is availbe due to ring exhaustion

Fixes #50

### CODE REVIEW

File: src/noise/timers.rs [hunk 1]
```diff
@@ -161,6 +173,8 @@ impl Tunn {
         let now = time.duration_since(timers.time_started);
         timers[TimeCurrent].set(now);
 
+        self.update_session_timers(now);
+
         // Load timers only once:
         let session_established = timers[TimeSessionEstablished].time();
         let handshake_started = timers[TimeLastHandshakeStarted].time();
```
Comment (Lekensteyn) [inline src/noise/timers.rs]: Maybe fix typos (aut_packet_received / aut_packet_sent) while at it?

Comment (vkrasnov) [reply src/noise/timers.rs]: what is the typo?

**Comment by cbranch** [comment]
> replay protection prevents attackers forcing use of an old session

okay, I just realised the counters are *per-session*. I think we should probably prevent roll-backs. Can do that in another PR.

**Comment by vkrasnov** [comment]
I now prevent that in here https://github.com/cloudflare/boringtun/pull/95/files#diff-282fdc1d310a41b65b6a16ba63f21652R386

File: src/noise/mod.rs [hunk 2]
```diff
@@ -382,24 +382,41 @@ impl Tunn {
         Ok(TunnResult::Done)
     }
 
+    // Update the index of the currently used session, if needed
+    fn set_current_session(&self, new_idx: usize) {
+        let cur_idx = self.current.load(Ordering::Relaxed);
```
Comment (kornelski) [inline src/noise/mod.rs]: I'm concerned about widespread use of `Relaxed` which gives no ordering guarantees. Especially that on x86 the hardware gives it more predictable behavior than the spec promises, so it may doubly blow up on ARM.

Unless ability to change the order of atomic operations is essential for performance, I'd prefer all such uses to use `SeqCst` just to be safe that they do what they seem to do.

Comment (vkrasnov) [reply src/noise/mod.rs]: I am aware of the memory model. We really don't care about the exact ordering of counters here, as long as they move forward in general.

Comment (vkrasnov) [reply src/noise/mod.rs]: And on ARM it matters for performance
