### PR TITLE
Fail hard and exit with error on startup failures

### LINKED ISSUE #48: Improve error checking paths during startup
In `src/main.rs`, there are some code paths that ignore errors. Among the possibly problematic ones are:

* When run as root, any failure to change user/group IDs will not result in a fatal error. This might might increase the risk of running with unnecessary privileged. (btw, the option name is misspelled, #43 was incomplete.)
```rust
    if !matches.is_present("disable-drop-priviliges") {
        drop_privileges().ok();
    }
```
* When running backgrounded (without `--foreground`), any errors will result in the application being foregrounded anyway. This may be contrary to user expectations.
```rust
        match daemonize.start() {
            Ok(_) => println!("Success, daemonized"),
            Err(e) => eprintln!("Error, {}", e),
        }
```

### PR DESCRIPTION
**Pull request by vkrasnov**
Fixes #48

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -109,20 +110,20 @@ fn main() {
...
-                    "{}",
-                    match b[0] {
-                        0 => "boringtun failed to start",
-                        _ => "boringtun started successfully",
-                    }
-                );
+                if sock2.recv(&mut b).is_ok() && b[0] == 1 {
+                    println!("BoringTun started successfully");
+                } else {
+                    println!("BoringTun failed to start");
```
Comment (kornelski) [inline src/main.rs]: `eprintln`
